version: "3"
services:
  auth:
    build: ./auth-api
    ports: 
      - "80:80"
  users:
    build: ./users-api
    ports: 
      - "9000:9000"
  tasks:
    build: ./tasks-api
    ports: 
      - "8000:8000"
    environment:
      TASKS_FOLDER: tasks
    
